### ISSUE TITLE
Unable to train the model for En-De translation

### ISSUE THREAD

**Issue by sugeeth14** [bzhangGo/zero#1]
Hi I tried the steps presented [here](https://github.com/bzhangGo/zero#how-to-use-it) completely until I train the model with the command 
`python zero/config.py --mode train --parameters=hidden_size=1024,embed_size=512,dropout=0.1,label_smooth=0.1,max_len=80,batch_size=80,eval_batch_size=240,token_size=3000,batch_or_token='token',model_name="rnnsearch",buffer_size=3200,clip_grad_norm=5.0,lrate=5e-4,epoches=25,update_cycle=8,gpus=[8],disp_freq=100,eval_freq=10000,sample_freq=1000,checkpoints=5,caencoder=True,cell='atr',max_training_steps=100000000,nthreads=8,swap_memory=True,layer_norm=True,max_queue_size=100,random_seed=1234,src_vocab_file="$data_dir/vocab.en",tgt_vocab_file="$data_dir/vocab.de",src_train_file="$data_dir/train.40k.en",tgt_train_file="$data_dir/train.40k.de",src_dev_file="$data_dir/dev.40k.en",tgt_dev_file="$data_dir/dev.40k.de",src_test_file="",tgt_test_file="",output_dir="train",test_output=""`

But I get the following error and training doesn't start
```
Traceback (most recent call last):
  File "zero/config.py", line 223, in <module>
    tf.app.run()
  File "/miniconda3/envs/myenv_s_m/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/miniconda3/envs/myenv_s_m/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/miniconda3/envs/myenv_s_m/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "zero/config.py", line 215, in main
    graph.train(params)
  File "/Sugeeth/translation_from_atr/zero/main.py", line 108, in train
    loss, gradients = tower_train_graph(train_features, optimizer, params)
  File "/Sugeeth/translation_from_atr/zero/main.py", line 35, in tower_train_graph
    params.gpus, use_cpu=(len(params.gpus) == 0))
  File "/Sugeeth/translation_from_atr/zero/utils/parallel.py", line 179, in parallel_model
    features, device_mask = shard_features(features, num_devices)
  File "/Sugeeth/translation_from_atr/zero/utils/parallel.py", line 132, in shard_features
    pieces = util.uniform_splits(tf.shape(features.values()[0])[0],
TypeError: 'dict_values' object does not support indexing
```

Did I miss something ?

**Comment by bzhangGo** [comment]
One possible reason is the python version. This code is based on python2.7, not python3.6.

**Comment by sugeeth14** [comment]
Thanks for the reply I tried using python2.7 but I got into another error which I guess has nothing to do with this repository 
```
2019-08-04 08:42:47.292998: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Internal: no supported devices found for platform CUDA
Aborted
```
I shall try to fix the error and train it. Also I wanted to use the [ATR](https://github.com/bzhangGo/ATR) network as part of fairseq library by trying to replace the LSTM part with the ATR network but since ATR expects PackedSequence as input compared to nn.LSTM which accepts both PackedSequence as well as inputs ( I might be wrong as well) . So you have any suggestions for trying to use ATR as a model in fairseq.

**Comment by bzhangGo** [comment]
*About using ATR in Fairseq*

The input to ATR and LSTM should be the same. You can use both PackedSequence or the raw inputs, depending on how you handle batches of different lengths. 

Here is an implementation of RNN with different recurrent cells [ATR](https://github.com/bzhangGo/lrn/blob/master/lm/code/rnn.py#L70). You can take it as an example, and work on your model. One noticeable thing is that the LSTM in pytorch, i.e. nn.LSTM, is highly Cuda optimized and is very fast. The given source code is based on vanilla pytorch DL library, could be significantly slower than nn.LSTM.
