### ISSUE TITLE
pretrained models and preprocessed data for CLSR at ICLR2021 are unavaliable

### ISSUE THREAD

**Issue by ZhaoCinyu** [bzhangGo/zero#10]
I'm having trouble finding the Google Drive URL for pretrained models, and it appears that there isn't any preprocessed data available in https://data.statmt.org/bzhang/iclr2021_share_or_not/. Is there another way to download them?

**Comment by bzhangGo** [comment]
Hey @ZhaoCinyu, I'm afraid the data was lost. The storage disk for our data was crashed and can't be recovered.
