### ISSUE TITLE
Vanishing Gradient Analysis

### ISSUE THREAD

**Issue by stephanpeitz** [bzhangGo/zero#2]
Hi Biao,

is there a convenient way to reproduce Table 1 from your paper "Improving Deep Transformer with Depth-Scaled Initialization and Merged Attention"?

Thanks a lot!

Cheers,
Stephan

**Comment by bzhangGo** [comment]
Hi Stephan,

there is no "one-click-for-all" script to get all the numbers in Table 1, and in the released source code, I didn't include the analysis codes.

I guess the main puzzling part is the calculation of <img src="https://latex.codecogs.com/svg.latex?\delta(r)"/> or similar.   I used some tricks inspired by simple linear mapping, 

<img src="https://latex.codecogs.com/svg.latex?y=Wx+b"/> 
This linear layer has the following properties:
<img src="https://latex.codecogs.com/svg.latex?\frac{\partial{y}}{\partial{b}}=1"/> such that  <img src="https://latex.codecogs.com/svg.latex?grad(b)=\delta(y)"/>

I did a similar thing to get the numbers in Table 1:
```
                    x = func.residual_fn(x, y, dropout=params.residual_dropout)
                    x_set = tf.get_variable("pre_offset", [hidden_size],
                                 initializer=tf.zeros_initializer())
                    x = x + x_set
```
In this way, we can obtain  <img src="https://latex.codecogs.com/svg.latex?||\delta(r)||"/> as <img src="https://latex.codecogs.com/svg.latex?||grad(x_{set})||"/>. 

best,
Biao
