### ISSUE TITLE
Speech data preprocessing

### ISSUE THREAD

**Issue by staehlmich** [bzhangGo/zero#6]
Hi

I'm using your AFS ST model as a baseline for my thesis project. I'm trying to run the speech preprocessing script, but the tensorflow.contrib package has been deprecated in tensorflow 2.0. Any suggestions on how to adapt your code?

Thank you!

**Comment by bzhangGo** [comment]
Hi,

the source code, including the preprocessing script and the main code, is based on tf1.13. If you plan to use this codebase for your experiments, I suggest you change your working environment to tf1.13 as well, e.g. using conda.

Or, If you only want to make the preprocessing script compatible with tf2.0, you need to modify `t2t_speech.py`. Here is a dirty solution:
1. change `hparams = get_hparams(tc.training.HParams())` (line 565) to `hparams = get_hparams(lambda : None)`
2. change `p.add_hparam(attr, value)` (line 192) to ` setattr(p, attr, value)`

**Comment by staehlmich** [comment]
Hi, 

I tried your first solution and ran the preprocessing script on a tf.1.3 environment. I ran into an error, that `.signal` method is not part of Tensorflow core.  `.signal` can be found in `tf.contrib` since tf1.5. I was able to successfully run the script in a tf1.9 environment.

Thanks!
