### ISSUE TITLE
tensorflow installation for Share or Not? Learning to Schedule Language-Specific Capacity for Multilingual Translation (Zhang et al., ICLR2021)

### ISSUE THREAD

**Issue by zide05** [bzhangGo/zero#7]
To reproduce the result in Share or Not? Learning to Schedule Language-Specific Capacity for Multilingual Translation (Zhang et al., ICLR2021), environment are required as :
- python==2.7
- tensorflow==1.13.1
but the tensorflow 1.13.1 simply can not be imported for python 2.7

**Comment by bzhangGo** [comment]
Hi,

You need to install tensorflow 1.13.1. For example,

```
# prepare your python environment
conda create --name py27 python=2.7
conda activate py27
# install tensorflow
pip install tensorflow==1.13.1
```

**Comment by zide05** [comment]
Thanks a lot for your reply,  i have noticed that the reason for tensorflow==1.13.1 can't work with python 2.7 is that the latest version of dependency package protobuf is not suitable for python2.7,  just install version 3.17.0 not 3.18.0 will solve the problem.
