### ISSUE TITLE
Using the provided sentencepiece model from multilingual_laln_lalt but the vocab size is 200k.

### ISSUE THREAD

**Issue by SefaZeng** [bzhangGo/zero#8]
I followed the README guide of multilingual_laln_lalt. And I download the provided sentencepiece model to encode the corpus. After that I try to build the vocab.zero.src and vocab.zero.tgt, but the output vocab size is 200k+ ? And I try to train a new sentencepiece model via the scripts but the BLEU score is lower than the result in the paper.

**Comment by bzhangGo** [comment]
Hi @SefaZeng,

Thanks for your question! 

* Regarding the vocabulary problem

  Apparently, 200k+ is abnormal. Could you please show more details on how you applied the sentencepiece model and how you constructed the vocab files? In our setup, we first applied the sentencepiece to convert the text file into its id counterpart, based on which we created the vocab.zero.*. The size of the vocabulary should be around 64K!

  You could have a look at [the-used-data-in-our-paper](https://data.statmt.org/bzhang/acl2020_multilingual/data-used-in-our-paper/) for reference.

* Regarding the BLEU scores

  Could you elaborate on your question a little bit more? For example, which setup are you using, O2M or M2O? which test language pair(s) did you evaluate? Also, what's your setting for the sentencepiece training? 

Best,
Biao

**Comment by SefaZeng** [comment]
> 
Basically, I download the opus data from [here](https://opus.nlpl.eu/opus-100.php) sentencepiece model from [here](https://github.com/bzhangGo/zero/tree/master/docs/multilingual_laln_lalt). Then I put it to the path of $data/many-to-many and $data/one-to-many.
Next, I use this command: 
`$zero_path/scripts/data/prepare_multilingual_translation.sh $opus_path $zero_path yes ${data}`
I commented out the part about spm_train.py . Then the output vocab.zero.src is about 200k lines.

About the BLEU scores, I experimented in a M2M type and I evaluate all the supervised directions which are 188. I build a new sp model with `prepare_multilingual_translation.sh` and it seems it works well as I set the batch size to 128 * 4096 tokens.

**Comment by bzhangGo** [comment]
Thanks, @SefaZeng!

We offered the sentencepiece model here mainly to allow the others to reuse or test our pretrained models. Different from `prepare_multilingual_translation.sh`, we used it in another way in our paper: we first converted text data into their BPE ids by setting `--output_format=id` to spm_encode; and then treat these id sequences as text, on top of which we trained our model. You could check out [here](https://data.statmt.org/bzhang/acl2020_multilingual/data-used-in-our-paper/) for reference. As a consequence, if the others want to try our pretrained model, the sentencepiece model will be required to preprocess the source inputs and also postprocess the target outputs.

It seems that you re-trained a sp model, which works. Please let me know if you get any other problems!
